# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x86
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x86)
  CoreSDK_config = debug_x86
  RuntimeSDK_config = debug_x86
  TestSDK_config = debug_x86

else ifeq ($(config),debug_x64)
  CoreSDK_config = debug_x64
  RuntimeSDK_config = debug_x64
  TestSDK_config = debug_x64

else ifeq ($(config),debug_arm32)
  CoreSDK_config = debug_arm32
  RuntimeSDK_config = debug_arm32
  TestSDK_config = debug_arm32

else ifeq ($(config),debug_arm64)
  CoreSDK_config = debug_arm64
  RuntimeSDK_config = debug_arm64
  TestSDK_config = debug_arm64

else ifeq ($(config),release_x86)
  CoreSDK_config = release_x86
  RuntimeSDK_config = release_x86
  TestSDK_config = release_x86

else ifeq ($(config),release_x64)
  CoreSDK_config = release_x64
  RuntimeSDK_config = release_x64
  TestSDK_config = release_x64

else ifeq ($(config),release_arm32)
  CoreSDK_config = release_arm32
  RuntimeSDK_config = release_arm32
  TestSDK_config = release_arm32

else ifeq ($(config),release_arm64)
  CoreSDK_config = release_arm64
  RuntimeSDK_config = release_arm64
  TestSDK_config = release_arm64

else ifeq ($(config),dist_x86)
  CoreSDK_config = dist_x86
  RuntimeSDK_config = dist_x86
  TestSDK_config = dist_x86

else ifeq ($(config),dist_x64)
  CoreSDK_config = dist_x64
  RuntimeSDK_config = dist_x64
  TestSDK_config = dist_x64

else ifeq ($(config),dist_arm32)
  CoreSDK_config = dist_arm32
  RuntimeSDK_config = dist_arm32
  TestSDK_config = dist_arm32

else ifeq ($(config),dist_arm64)
  CoreSDK_config = dist_arm64
  RuntimeSDK_config = dist_arm64
  TestSDK_config = dist_arm64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := CoreSDK RuntimeSDK TestSDK

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

CoreSDK:
ifneq (,$(CoreSDK_config))
	@echo "==== Building CoreSDK ($(CoreSDK_config)) ===="
	@${MAKE} --no-print-directory -C CoreSDK -f Makefile config=$(CoreSDK_config)
endif

RuntimeSDK: CoreSDK
ifneq (,$(RuntimeSDK_config))
	@echo "==== Building RuntimeSDK ($(RuntimeSDK_config)) ===="
	@${MAKE} --no-print-directory -C RuntimeSDK -f Makefile config=$(RuntimeSDK_config)
endif

TestSDK: CoreSDK
ifneq (,$(TestSDK_config))
	@echo "==== Building TestSDK ($(TestSDK_config)) ===="
	@${MAKE} --no-print-directory -C TestSDK -f Makefile config=$(TestSDK_config)
endif

clean:
	@${MAKE} --no-print-directory -C CoreSDK -f Makefile clean
	@${MAKE} --no-print-directory -C RuntimeSDK -f Makefile clean
	@${MAKE} --no-print-directory -C TestSDK -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x86"
	@echo "  debug_x64"
	@echo "  debug_arm32"
	@echo "  debug_arm64"
	@echo "  release_x86"
	@echo "  release_x64"
	@echo "  release_arm32"
	@echo "  release_arm64"
	@echo "  dist_x86"
	@echo "  dist_x64"
	@echo "  dist_arm32"
	@echo "  dist_arm64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   CoreSDK"
	@echo "   RuntimeSDK"
	@echo "   TestSDK"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"