# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x86
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x86)
  FiberJobSystem_config = debug_x86
  FiberJobSystemTests_config = debug_x86
  FiberJobSystemPerformance_config = debug_x86
  AOSHLL_config = debug_x86
  AOSHLLTests_config = debug_x86

else ifeq ($(config),debug_x64)
  FiberJobSystem_config = debug_x64
  FiberJobSystemTests_config = debug_x64
  FiberJobSystemPerformance_config = debug_x64
  AOSHLL_config = debug_x64
  AOSHLLTests_config = debug_x64

else ifeq ($(config),debug_arm32)
  FiberJobSystem_config = debug_arm32
  FiberJobSystemTests_config = debug_arm32
  FiberJobSystemPerformance_config = debug_arm32
  AOSHLL_config = debug_arm32
  AOSHLLTests_config = debug_arm32

else ifeq ($(config),debug_arm64)
  FiberJobSystem_config = debug_arm64
  FiberJobSystemTests_config = debug_arm64
  FiberJobSystemPerformance_config = debug_arm64
  AOSHLL_config = debug_arm64
  AOSHLLTests_config = debug_arm64

else ifeq ($(config),release_x86)
  FiberJobSystem_config = release_x86
  FiberJobSystemTests_config = release_x86
  FiberJobSystemPerformance_config = release_x86
  AOSHLL_config = release_x86
  AOSHLLTests_config = release_x86

else ifeq ($(config),release_x64)
  FiberJobSystem_config = release_x64
  FiberJobSystemTests_config = release_x64
  FiberJobSystemPerformance_config = release_x64
  AOSHLL_config = release_x64
  AOSHLLTests_config = release_x64

else ifeq ($(config),release_arm32)
  FiberJobSystem_config = release_arm32
  FiberJobSystemTests_config = release_arm32
  FiberJobSystemPerformance_config = release_arm32
  AOSHLL_config = release_arm32
  AOSHLLTests_config = release_arm32

else ifeq ($(config),release_arm64)
  FiberJobSystem_config = release_arm64
  FiberJobSystemTests_config = release_arm64
  FiberJobSystemPerformance_config = release_arm64
  AOSHLL_config = release_arm64
  AOSHLLTests_config = release_arm64

else ifeq ($(config),dist_x86)
  FiberJobSystem_config = dist_x86
  FiberJobSystemTests_config = dist_x86
  FiberJobSystemPerformance_config = dist_x86
  AOSHLL_config = dist_x86
  AOSHLLTests_config = dist_x86

else ifeq ($(config),dist_x64)
  FiberJobSystem_config = dist_x64
  FiberJobSystemTests_config = dist_x64
  FiberJobSystemPerformance_config = dist_x64
  AOSHLL_config = dist_x64
  AOSHLLTests_config = dist_x64

else ifeq ($(config),dist_arm32)
  FiberJobSystem_config = dist_arm32
  FiberJobSystemTests_config = dist_arm32
  FiberJobSystemPerformance_config = dist_arm32
  AOSHLL_config = dist_arm32
  AOSHLLTests_config = dist_arm32

else ifeq ($(config),dist_arm64)
  FiberJobSystem_config = dist_arm64
  FiberJobSystemTests_config = dist_arm64
  FiberJobSystemPerformance_config = dist_arm64
  AOSHLL_config = dist_arm64
  AOSHLLTests_config = dist_arm64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := FiberJobSystem FiberJobSystemTests FiberJobSystemPerformance AOSHLL AOSHLLTests

.PHONY: all clean help $(PROJECTS) BenchMarks Tests

all: $(PROJECTS)

BenchMarks: AOSHLL FiberJobSystemPerformance

Tests: AOSHLLTests FiberJobSystemTests

FiberJobSystem:
ifneq (,$(FiberJobSystem_config))
	@echo "==== Building FiberJobSystem ($(FiberJobSystem_config)) ===="
	@${MAKE} --no-print-directory -C ../FiberJobSystem -f FiberJobSystem.make config=$(FiberJobSystem_config)
endif

FiberJobSystemTests: FiberJobSystem
ifneq (,$(FiberJobSystemTests_config))
	@echo "==== Building FiberJobSystemTests ($(FiberJobSystemTests_config)) ===="
	@${MAKE} --no-print-directory -C ../FiberJobSystem -f FiberJobSystemTests.make config=$(FiberJobSystemTests_config)
endif

FiberJobSystemPerformance: FiberJobSystem
ifneq (,$(FiberJobSystemPerformance_config))
	@echo "==== Building FiberJobSystemPerformance ($(FiberJobSystemPerformance_config)) ===="
	@${MAKE} --no-print-directory -C ../FiberJobSystem -f FiberJobSystemPerformance.make config=$(FiberJobSystemPerformance_config)
endif

AOSHLL:
ifneq (,$(AOSHLL_config))
	@echo "==== Building AOSHLL ($(AOSHLL_config)) ===="
	@${MAKE} --no-print-directory -C ../AOSHLL -f AOSHLL.make config=$(AOSHLL_config)
endif

AOSHLLTests: AOSHLL
ifneq (,$(AOSHLLTests_config))
	@echo "==== Building AOSHLLTests ($(AOSHLLTests_config)) ===="
	@${MAKE} --no-print-directory -C ../AOSHLL -f AOSHLLTests.make config=$(AOSHLLTests_config)
endif

clean:
	@${MAKE} --no-print-directory -C ../FiberJobSystem -f FiberJobSystem.make clean
	@${MAKE} --no-print-directory -C ../FiberJobSystem -f FiberJobSystemTests.make clean
	@${MAKE} --no-print-directory -C ../FiberJobSystem -f FiberJobSystemPerformance.make clean
	@${MAKE} --no-print-directory -C ../AOSHLL -f AOSHLL.make clean
	@${MAKE} --no-print-directory -C ../AOSHLL -f AOSHLLTests.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x86"
	@echo "  debug_x64"
	@echo "  debug_arm32"
	@echo "  debug_arm64"
	@echo "  release_x86"
	@echo "  release_x64"
	@echo "  release_arm32"
	@echo "  release_arm64"
	@echo "  dist_x86"
	@echo "  dist_x64"
	@echo "  dist_arm32"
	@echo "  dist_arm64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   FiberJobSystem"
	@echo "   FiberJobSystemTests"
	@echo "   FiberJobSystemPerformance"
	@echo "   AOSHLL"
	@echo "   AOSHLLTests"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"